#!/bin/bash
#
# DESCRIPTION:
# This file provides different prompt styles in form of bash functions.
#
# USAGE:
# o source this file
# o use 'prompt_store' to save your current prompt
# o use a function beginning with 'prompt_' to set a new style
# o find out which style you are using with 'prompt_name'
# o restore your old prompt using 'prompt_restore'
#
# CHANGELOG:
# 10/06/01 added ben, zero, time
# 07/08/14 started with a concept of somewhat around Jan 2005
#          added steppy and shorty (from old concept) 
#          added timmy, standard, jack, peter, paul, mary, littlepaul,
#          mini, mickey, power, mono and zip.

## BOLD COLOURS
UNDERLB="\[\033[1;38m\]"
GRAY="\[\033[1;30m\]"
REDB="\[\033[1;31m\]"
GREENB="\[\033[1;32m\]"
YELLOWB="\[\033[1;33m\]"
BLUEB="\[\033[1;34m\]"
VIOB="\[\033[1;35m\]"
CYANB="\[\033[1;36m\]"
WHITEB="\[\033[1;37m\]"
## NORMAL COLOURS
UNDERL="\[\033[0;38m\]"
BLACK="\[\033[0;30m\]"
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
VIO="\[\033[0;35m\]"
CYAN="\[\033[0;36m\]"
WHITE="\[\033[0;37m\]"
## BACKGROUNDS
BG_BLACK="\[\033[0;40m\]"
BG_RED="\[\033[0;41m\]"
BG_GREEN="\[\033[0;42m\]"
BG_YELLOW="\[\033[0;43m\]"
BG_BLUE="\[\033[0;44m\]"
BG_VIO="\[\033[0;45m\]"
BG_CYAN="\[\033[0;46m\]"
BG_WHITE="\[\033[0;47m\]"
## OTHER ESCAPES
NOCOL="\[\033[0m\]"

alias prompt_store='export OLDPS1=$PS1'

function prompt_restore()
{
	if [ -n "$OLDPS1" ];then
		export PS1=$OLDPS1
	fi
}

alias prompt_name='echo $PROMPTSTYLE_NAME'

function prompt_steppy()
{
	PS1="[$BLUEB\$(date +%H:%M\ %x)$NOCOL][$GREEN\w$NOCOL]\n[\u@\h]"'\$ '
	export PROMPTSTYLE_NAME="steppy"
}

function prompt_shorty()
{
   PS1="$GREENB\u@\h $BLUEB\W "'\$'" $NOCOL"
	export PROMPTSTYLE_NAME="shorty"
}

function prompt_timmy()
{
	PS1="[\$(date +%H%M)][\u@\h: \W]"'\$ '
	export PROMPTSTYLE_NAME="timmy"
}

function prompt_standard()
{
	PS1="$GREENB\u@\h: $NOCOL\w "'\$ '
	export PROMPTSTYLE_NAME="standard"
}

function prompt_jack()
{
	if [ -x "/usr/bin/apm" ];then
		battery="$GRAY| $NOCOL@\$(apm | tr -d '[:alpha:]-,: ')$GRAY "
	fi
	local terminal=`tty | tr -d '/dev'`
PS1="$GRAY[$NOCOL\$(date +%a,\ %d.%m.,\ %H:%M) \
$GRAY| $NOCOL$terminal \
$battery\
$GRAY| $NOCOL\w (\$(ls | wc -l))$GRAY]\n\
$GRAY[$GREENB\u@\h$GRAY] $NOCOL"'\$ ' 
	export PROMPTSTYLE_NAME="jack"
}

function prompt_peter()
{
	if [ -x "/usr/bin/apm" ];then
		battery="$BLUEB@\$(apm | tr -d '[:alpha:]-,: ') "
	fi
	PS1="$WHITEB\$(pwd)\n$battery$GRAY\$(date +%H:%M) $NOCOL\u@\h "'\$ '
	export PROMPTSTYLE_NAME="peter"
}

function prompt_paul()
{
	if [ -x "/usr/bin/apm" ];then
		battery=" (@\$(apm | tr -d '[:alpha:]-,: '))"
	fi
	PS1="(\$(date +%H:%M,\ %D))$battery\n$GREEN\u@\h$NOCOL: $UNDERL\w$NOCOL"' \$ '
	export PROMPTSTYLE_NAME="paul"
}

function prompt_mary()
{
	if [ -x "/usr/bin/apm" ];then
		battery="$BLUEB[$GRAY@\$(apm | tr -d '[:alpha:]-,: ')$BLUEB]-"
	fi
	PS1="$battery""$BLUEB[$GRAY\$(date +%H:%M,\ %D)$BLUEB]\n$BLUEB[$REDB\u@\h$BLUEB]-$BLUEB[$WHITEB\w$BLUEB""]$NOCOL"'\$ '
}

function prompt_littlepaul()
{
	PS1="$GREEN\u@\h$NOCOL: $UNDERL\w$NOCOL"' \$ '
	export PROMPTSTYLE_NAME="littlepaul"
}

function prompt_mini()
{
	PS1="$GREENB\u $BLUEB\W$NOCOL"' \$ '
	export PROMPTSTYLE_NAME="mini"
}

function prompt_mickey()
{
	if [ -x "/usr/bin/apm" ];then
		battery="@\$(apm | tr -d '[:alpha:]-,: ') "
	fi

	PS1="$battery$YELLOWB\$(date +%H:%M) $GREENB\u $BLUEB\W$NOCOL"' \$ '
	export PROMPTSTYLE_NAME="mickey"
}

function prompt_power()
{
	if [ -x "/usr/bin/apm" ];then
		battery="-($NOCOL@\$(apm | tr -d '[:alpha:]-,: ')$GREEN)-"
	fi
	local terminal=`tty | tr -d '/dev'`
PS1="$GREEN($NOCOL\u@\h$GREEN)\
$battery\
($NOCOL$terminal$GREEN)\
-($NOCOL\j jobs$GREEN)\
-($NOCOL\$(ls | wc -l) in \$(pwd)$GREEN)\n\
$GREEN($NOCOL\$(date +%H%M%S)$GREEN)-"'\$ '$NOCOL
	export PROMPTSTYLE_NAME="power"
}

function prompt_mono()
{
	if [ -x "/usr/bin/apm" ];then
		battery="$NOCOL@\$(apm | tr -d '[:alpha:]-,: ')$WHITEB | "
	fi
PS1="$WHITEB[$NOCOL\u@\h$WHITEB | $battery$NOCOL\$(date +%H:%M)$WHITEB]\
\n$WHITEB[$NOCOL\W (\$(ls | wc -l))$WHITEB]$NOCOL"'\$ '
	export PROMPTSTYLE_NAME="mono"
}

function prompt_zip()
{
	PS1="$GREENB\u$NOCOL: $BLUEB\W $NOCOL(\$(ls | wc -l))"'\$ '
	export PROMPTSTYLE_NAME="zip"
}

function prompt_ben()
{
	PS1="\$(date +%H%M) $GREENB\h:$BLUEB\W$NOCOL"'\$ '
	export PROMPTSTYLE_NAME="ben"
}

function prompt_zero()
{
	PS1="$BLUEB"'\$'"$NOCOL "
	export PROMPTSTYLE_NAME="zero"
}

function prompt_time()
{
	PS1="$BLUE\$(date +%H:%M) "'\$'"$NOCOL "
	export PROMPTSTYLE_NAME="time"
}

